# Generated by Django 2.2.7 on 2019-11-08 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('store', 'date')},
        ),
        migrations.AlterModelOptions(
            name='invoicedetail',
            options={'ordering': ('invoice__store', 'invoice__date')},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('name', 'description')},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('name', 'lastName', 'identification')},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ('store',)},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('name',)},
        ),
    ]
