#!/bin/sh

psql -U postgres -c "CREATE USER $DB_USERNAME PASSWORD '$DB_PASSWORD'"
psql -U postgres -c "CREATE DATABASE $DB_NAME OWNER $DB_USERNAME"
psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USERNAME"
